# Generated by Django 3.2.8 on 2021-10-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], verbose_name='Gender'),
        ),
    ]
